In [1]:
import scanpy as sc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = sc.read_h5ad('/Users/evanli/Documents/Research_datasets/PBMC_Hao/Hao_PBMC.h5ad')
data.shape

(161764, 20568)

In [3]:
# reverse log1p transformation
# np.expm1: exp(x) - 1 (is the inverse function of log1p)
data.X = np.expm1(data.X)

In [4]:
type(data.X)

scipy.sparse.csr.csr_matrix

In [5]:
data.obs.head(10)  # 161764

nCount_ADT  nFeature_ADT  nCount_RNA  nFeature_RNA  \
L1_AAACCCAAGAAACTCA      7430.0           221     10823.0          2915   
L1_AAACCCAAGACATACA      5949.0           211      5864.0          1617   
L1_AAACCCACAACTGGTT      6547.0           217      5067.0          1381   
L1_AAACCCACACGTACTA      3508.0           207      4786.0          1890   
L1_AAACCCACAGCATACT      6318.0           219      6505.0          1621   
L1_AAACCCACATCAGTCA      5195.0           213      4332.0          1633   
L1_AAACCCACATCGGTTA      7507.0           223      9333.0          2672   
L1_AAACCCACATGGATCT      8138.0           226      3589.0          1122   
L1_AAACCCAGTGGAACAC      2858.0           205      3251.0          1375   
L1_AAACCCATCCACACCT      4501.0           210      3401.0          1200   

                    orig.ident lane donor_id time celltype.l1     celltype.l2  \
L1_AAACCCAAGAAACTCA       P2_7   L1       P2    7        Mono       CD14 Mono   
L1_AAACCCAAGACATACA       P1_7   L1       P1    7       CD4 T         CD4 TCM   
L1_AAACCCACAACTGGTT       P4_3   L1       P4    3       CD8 T       CD8 Naive   
L1_AAACCCACACGTACTA       P3_7   L1       P3    7          NK              NK   
L1_AAACCCACAGCATACT       P4_7   L1       P4    7       CD8 T       CD8 Naive   
L1_AAACCCACATCAGTCA       P3_3   L1       P3    3       CD8 T         CD8 TEM   
L1_AAACCCACATCGGTTA       P1_7   L1       P1    7        Mono       CD16 Mono   
L1_AAACCCACATGGATCT       P4_3   L1       P4    3           B  B intermediate   
L1_AAACCCAGTGGAACAC       P1_3   L1       P1    3          NK              NK   
L1_AAACCCATCCACACCT       P3_3   L1       P3    3       CD8 T       CD8 Naive   

                     ... tissue_ontology_term_id suspension_type  \
L1_AAACCCAAGAAACTCA  ...          UBERON:0000178            cell   
L1_AAACCCAAGACATACA  ...          UBERON:0000178            cell   
L1_AAACCCACAACTGGTT  ...          UBERON:0000178            cell   
L1_AAACCCACACGTACTA  ...          UBERON:0000178            cell   
L1_AAACCCACAGCATACT  ...          UBERON:0000178            cell   
L1_AAACCCACATCAGTCA  ...          UBERON:0000178            cell   
L1_AAACCCACATCGGTTA  ...          UBERON:0000178            cell   
L1_AAACCCACATGGATCT  ...          UBERON:0000178            cell   
L1_AAACCCAGTGGAACAC  ...          UBERON:0000178            cell   
L1_AAACCCATCCACACCT  ...          UBERON:0000178            cell   

                                                             cell_type  \
L1_AAACCCAAGAAACTCA                             CD14-positive monocyte   
L1_AAACCCAAGACATACA     central memory CD4-positive, alpha-beta T cell   
L1_AAACCCACAACTGGTT  naive thymus-derived CD8-positive, alpha-beta ...   
L1_AAACCCACACGTACTA                                natural killer cell   
L1_AAACCCACAGCATACT  naive thymus-derived CD8-positive, alpha-beta ...   
L1_AAACCCACATCAGTCA    effector memory CD8-positive, alpha-beta T cell   
L1_AAACCCACATCGGTTA                   CD14-low, CD16-positive monocyte   
L1_AAACCCACATGGATCT                                             B cell   
L1_AAACCCAGTGGAACAC                                natural killer cell   
L1_AAACCCATCCACACCT  naive thymus-derived CD8-positive, alpha-beta ...   

                         assay disease      organism      sex tissue  \
L1_AAACCCAAGAAACTCA  10x 3' v3  normal  Homo sapiens  unknown  blood   
L1_AAACCCAAGACATACA  10x 3' v3  normal  Homo sapiens  unknown  blood   
L1_AAACCCACAACTGGTT  10x 3' v3  normal  Homo sapiens  unknown  blood   
L1_AAACCCACACGTACTA  10x 3' v3  normal  Homo sapiens  unknown  blood   
L1_AAACCCACAGCATACT  10x 3' v3  normal  Homo sapiens  unknown  blood   
L1_AAACCCACATCAGTCA  10x 3' v3  normal  Homo sapiens  unknown  blood   
L1_AAACCCACATCGGTTA  10x 3' v3  normal  Homo sapiens  unknown  blood   
L1_AAACCCACATGGATCT  10x 3' v3  normal  Homo sapiens  unknown  blood   
L1_AAACCCAGTGGAACAC  10x 3' v3  normal  Homo sapiens  unknown  blood   
L1_AAACCCATCCACACCT

In [6]:
# row sum of data.X
row_sum = data.X.sum(axis=1)
row_sum[:10]  # equal to total_counts (not integer)

matrix([[6379.],
        [5692.],
        [5059.],
        [4979.],
        [5854.],
        [4934.],
        [6378.],
        [4489.],
        [4366.],
        [4722.]], dtype=float32)

In [7]:
row_sum.shape

(161764, 1)

In [8]:
# assuming data.X is your sparse CSR matrix
num_nonzero = data.X.getnnz(axis=1)
num_nonzero[:10]

array([2547, 1614, 1375, 1884, 1620, 1628, 2543, 1123, 1376, 1215],
      dtype=int32)

In [9]:
# QC metrics
sc.pp.calculate_qc_metrics(data, inplace=True)

In [10]:
data.obs.head(10)

nCount_ADT  nFeature_ADT  nCount_RNA  nFeature_RNA  \
L1_AAACCCAAGAAACTCA      7430.0           221     10823.0          2915   
L1_AAACCCAAGACATACA      5949.0           211      5864.0          1617   
L1_AAACCCACAACTGGTT      6547.0           217      5067.0          1381   
L1_AAACCCACACGTACTA      3508.0           207      4786.0          1890   
L1_AAACCCACAGCATACT      6318.0           219      6505.0          1621   
L1_AAACCCACATCAGTCA      5195.0           213      4332.0          1633   
L1_AAACCCACATCGGTTA      7507.0           223      9333.0          2672   
L1_AAACCCACATGGATCT      8138.0           226      3589.0          1122   
L1_AAACCCAGTGGAACAC      2858.0           205      3251.0          1375   
L1_AAACCCATCCACACCT      4501.0           210      3401.0          1200   

                    orig.ident lane donor_id time celltype.l1     celltype.l2  \
L1_AAACCCAAGAAACTCA       P2_7   L1       P2    7        Mono       CD14 Mono   
L1_AAACCCAAGACATACA       P1_7   L1       P1    7       CD4 T         CD4 TCM   
L1_AAACCCACAACTGGTT       P4_3   L1       P4    3       CD8 T       CD8 Naive   
L1_AAACCCACACGTACTA       P3_7   L1       P3    7          NK              NK   
L1_AAACCCACAGCATACT       P4_7   L1       P4    7       CD8 T       CD8 Naive   
L1_AAACCCACATCAGTCA       P3_3   L1       P3    3       CD8 T         CD8 TEM   
L1_AAACCCACATCGGTTA       P1_7   L1       P1    7        Mono       CD16 Mono   
L1_AAACCCACATGGATCT       P4_3   L1       P4    3           B  B intermediate   
L1_AAACCCAGTGGAACAC       P1_3   L1       P1    3          NK              NK   
L1_AAACCCATCCACACCT       P3_3   L1       P3    3       CD8 T       CD8 Naive   

                     ... self_reported_ethnicity development_stage  \
L1_AAACCCAAGAAACTCA  ...                 unknown           unknown   
L1_AAACCCAAGACATACA  ...                 unknown           unknown   
L1_AAACCCACAACTGGTT  ...                 unknown           unknown   
L1_AAACCCACACGTACTA  ...                 unknown           unknown   
L1_AAACCCACAGCATACT  ...                 unknown           unknown   
L1_AAACCCACATCAGTCA  ...                 unknown           unknown   
L1_AAACCCACATCGGTTA  ...                 unknown           unknown   
L1_AAACCCACATGGATCT  ...                 unknown           unknown   
L1_AAACCCAGTGGAACAC  ...                 unknown           unknown   
L1_AAACCCATCCACACCT  ...                 unknown           unknown   

                     n_genes_by_counts  log1p_n_genes_by_counts total_counts  \
L1_AAACCCAAGAAACTCA               2547                 7.843064       6379.0   
L1_AAACCCAAGACATACA               1614                 7.387090       5692.0   
L1_AAACCCACAACTGGTT               1375                 7.226936       5059.0   
L1_AAACCCACACGTACTA               1884                 7.541683       4979.0   
L1_AAACCCACAGCATACT               1620                 7.390799       5854.0   
L1_AAACCCACATCAGTCA               1628                 7.395722       4934.0   
L1_AAACCCACATCGGTTA               2543                 7.841493       6378.0   
L1_AAACCCACATGGATCT               1123                 7.024649       4489.0   
L1_AAACCCAGTGGAACAC               1376                 7.227662       4366.0   
L1_AAACCCATCCACACCT               1215                 7.103322       4722.0   

                    log1p_total_counts pct_counts_in_top_50_genes  \
L1_AAACCCAAGAAACTCA           8.760923                  33.531902   
L1_AAACCCAAGACATACA           8.646993                  44.448349   
L1_AAACCCACAACTGGTT           8.529121                  46.590235   
L1_AAACCCACACGTACTA           8.513186                  32.817835   
L1_AAACCCACAGCATACT           8.675052                  44.055347   
L1_AAACCCACATCAGTCA           8.504107                  37.474666   
L1_AAACCCACATCGGTTA           8.760767                  32.188774   
L1_AAACCCACATGGATCT           8.409608                  45.622633   
L1_AAACCCAGTGGAACAC           

## Garnett scaling on adata.X (not log transformed)

In [14]:
from scipy.stats import gmean
# a: total read counts per cell
a = data.obs['total_counts']

# assuming data.X is your sparse CSR matrix
D = gmean(a) / np.median(data.X.getnnz(axis=1))

In [15]:
D

3.3108369956438457

In [16]:
# Transform expression matrix M to N
M = data.X
median_g = np.median(M.getnnz(axis=1))
# total read counts per cell / D * median_g
f_j = M.sum(axis=1).A1 / (D * median_g)

# transformed N
N = M / f_j[:, None]  # convert 1D array f_j to 2D array

In [17]:
f_j.shape

(161764,)

In [19]:
f_j[:10]

array([0.95239896, 0.84982836, 0.75532   , 0.74337584, 0.8740153 ,
       0.73665726, 0.95224965, 0.67021775, 0.65185356, 0.70500517],
      dtype=float32)

In [27]:
f_j[-5:]

array([1.2278616, 1.2938532, 1.2760862, 1.3383453, 1.2750411],
      dtype=float32)

In [20]:
type(M)

scipy.sparse.csr.csr_matrix

In [21]:
type(N)

numpy.matrix

In [22]:
M.shape

(161764, 20568)

In [23]:
N.shape

(161764, 20568)

In [26]:
M.toarray()

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [25]:
N

matrix([[0.       , 1.0499802, 0.       , ..., 0.       , 0.       ,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ],
        ...,
        [0.       , 0.7836461, 0.       , ..., 0.       , 0.       ,
         0.       ],
        [0.       , 0.       , 0.7471913, ..., 0.       , 0.       ,
         0.       ],
        [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
         0.       ]], dtype=float32)

In [28]:
# turn into function
def garnett_scaling(M):
    # M is the original expression matrix, in sparse CSR format
    # transform expression matrix M to N

    # a: total read counts per cell
    a = data.obs['total_counts']

    # calculate D from M, or take D as input??
    D_size_factor = gmean(a) / np.median(M.getnnz(axis=1))

    median_g = np.median(M.getnnz(axis=1))
    f_j = M.sum(axis=1).A1 / (D_size_factor * median_g)
    N = M / f_j[:, None]
    
    return N