In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import json
import os

In [2]:
queue = ['CD4_T', 'DC', 'Mono', 'NK', 'CD8_T', 'B']
len(queue)

6

In [6]:
idx_dict = {'CD4_T': [15,16,17,20,21], 
            'DC': [16,19,21], 
            'Mono': [17,19,22], 
            'NK': [20,23], 
            'CD8_T': [21], 
            'B': [19]}

In [10]:
def convert_lists_to_arrays(dictionary):
    for key in dictionary:
        dictionary[key] = np.array(dictionary[key])
    return dictionary

In [36]:
# os.chdir('/home/jovyan/work/GitHub/EvanPys/Progress/PBMC_Hao_batch_noZ/Level1/tuning_result_cuda')
os.chdir(r"C:\Users\evanlee\Documents\GitHub\EvanPys\Progress\PBMC_Hao_batch_noZ\Level1\tuning_result_cuda")
# /Users/evanli/Documents/EvanPys/Progress/PBMC_Hao_batch_noZ/Level1/tuning_result_cuda
celltype = queue[0]
with open(f'{celltype}_tuning.json') as f:
    tuning = json.load(f)

tuning = convert_lists_to_arrays(tuning)
tuning.keys()

dict_keys(['Percentage', 'Prevalence', 'Feature_number', 'AUC', 'AUPR', 'MCC', 'Precision', 'F1 score', 'loss_history', 'error_history', 'log_lambda_range'])

In [37]:
idx = idx_dict[celltype]
tuning['Feature_number'][idx]

array([121.,  64.,  50.,  20.,  14.])

In [38]:
queue_lambda = tuning['log_lambda_range'][idx]
queue_lambda = np.exp(queue_lambda)
queue_lambda

array([0.00316228, 0.00464159, 0.00681292, 0.02154435, 0.03162278])

In [17]:
def get_lambdas_for_celltype(idx, tuning_filename):
    def convert_lists_to_arrays(dictionary):
        for key in dictionary:
            dictionary[key] = np.array(dictionary[key])
        return dictionary

    with open(tuning_filename) as f:
        tuning = json.load(f)
    tuning = convert_lists_to_arrays(tuning)

    queue_lambda = tuning['log_lambda_range'][idx]
    queue_lambda = np.exp(queue_lambda)
    return queue_lambda


In [19]:
lambda_dict = {}
for celltype, indices in idx_dict.items():
    tuning_filename = os.path.join(r"C:\Users\evanlee\Documents\GitHub\EvanPys\Progress\PBMC_Hao_batch_noZ\Level1\tuning_result_cuda", f'{celltype}_tuning.json')
    lambda_dict[celltype] = get_lambdas_for_celltype(indices, tuning_filename)
lambda_dict

{'CD4_T': array([0.00316228, 0.00464159, 0.00681292, 0.02154435, 0.03162278]),
 'DC': array([0.00464159, 0.01467799, 0.03162278]),
 'Mono': array([0.00681292, 0.01467799, 0.04641589]),
 'NK': array([0.02154435, 0.06812921]),
 'CD8_T': array([0.03162278]),
 'B': array([0.01467799])}

In [39]:
lambda_dict[celltype]

array([0.00316228, 0.00464159, 0.00681292, 0.02154435, 0.03162278])